CREATE DATABASE PRODATA;
USE PRODATA;
SELECT * FROM LAYOFFS;


# CTEATING NEW TABLE FOR WORKING
CREATE TABLE WORKING_LAYOFFS
LIKE LAYOFFS;

INSERT INTO WORKING_LAYOFFS SELECT * FROM LAYOFFS;
SELECT * FROM WORKING_LAYOFFS;

SELECT *, ROW_NUMBER() OVER(PARTITION BY COMPANY,LOCATION,INDUSTRY,TOTAL_LAID_OFF,PERCENTAGE_LAID_OFF,'DATE',
STAGE,COUNTRY,FUNDS_RAISED_MILLIONS) AS ROW_NUM 
FROM WORKING_LAYOFFS;

# REMOVING DUPLICATE
WITH DUPLICATE_CTE AS (
SELECT *, ROW_NUMBER() OVER(PARTITION BY COMPANY,LOCATION,INDUSTRY,TOTAL_LAID_OFF,PERCENTAGE_LAID_OFF,DATE,
STAGE,COUNTRY,FUNDS_RAISED_MILLIONS) AS ROW_NUM 
FROM WORKING_LAYOFFS
)SELECT * FROM DUPLICATE_CTE WHERE ROW_NUM>1;

SELECT * FROM WORKING_LAYOFFS WHERE COMPANY='ELEMY';SELECT `working_layoffs`.`company`,
    `working_layoffs`.`location`,
    `working_layoffs`.`industry`,
    `working_layoffs`.`total_laid_off`,
    `working_layoffs`.`percentage_laid_off`,
    `working_layoffs`.`date`,
    `working_layoffs`.`stage`,
    `working_layoffs`.`country`,
    `working_layoffs`.`funds_raised_millions`
FROM `prodata`.`working_layoffs`;



#CREATING NEW TABLE
CREATE TABLE `working_layoffs_2` (
  `company` text,
  `location` text,
  `industry` text,
  `total_laid_off` int DEFAULT NULL,
  `percentage_laid_off` text,
  `date` text,
  `stage` text,
  `country` text,
  `funds_raised_millions` int DEFAULT NULL,
  ROW_NUM INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;



INSERT INTO WORKING_LAYOFFS_2
SELECT *, ROW_NUMBER() OVER(PARTITION BY COMPANY,LOCATION,INDUSTRY,TOTAL_LAID_OFF,PERCENTAGE_LAID_OFF,DATE,
STAGE,COUNTRY,FUNDS_RAISED_MILLIONS) AS ROW_NUM 
FROM WORKING_LAYOFFS;

DELETE FROM WORKING_LAYOFFS_2 WHERE ROW_NUM>1;
SET SQL_SAFE_UPDATES=0;
SELECT * FROM WORKING_LAYOFFS_2;


#STANDARDIZING DATA


SELECT distinct(COMPANY) FROM WORKING_LAYOFFS_2 ORDER BY 1;
UPDATE WORKING_LAYOFFS_2
SET COMPANY=TRIM(COMPANY);

SELECT distinct(INDUSTRY) FROM WORKING_LAYOFFS_2 ORDER BY 1;

SELECT * FROM WORKING_LAYOFFS_2 WHERE INDUSTRY LIKE 'CRYPTO%';

UPDATE WORKING_LAYOFFS_2
SET INDUSTRY ='CRYPTO' WHERE INDUSTRY LIKE 'CRYPTO%';

SELECT distinct(LOCATION) FROM WORKING_LAYOFFS_2 ORDER BY 1;
SELECT distinct(COUNTRY) ,TRIM(TRAILING '.' FROM COUNTRY) FROM WORKING_LAYOFFS_2 ORDER BY 1;

UPDATE WORKING_LAYOFFS_2
SET COUNTRY =TRIM(TRAILING '.' FROM COUNTRY) WHERE COUNTRY LIKE 'UNITED STATES%';
SELECT distinct(COUNTRY) FROM WORKING_LAYOFFS_2 ORDER BY 1;

SELECT DATE,str_to_date(DATE,'%m/%d/%Y')
FROM WORKING_LAYOFFS_2;

UPDATE WORKING_LAYOFFS_2
SET DATE=str_to_date(DATE,'%m/%d/%Y');

SELECT DATE FROM WORKING_LAYOFFS_2;

ALTER TABLE WORKING_LAYOFFS_2 MODIFY COLUMN DATE DATE;


#HANDLING NULL VALUES

SELECT * FROM WORKING_LAYOFFS_2 WHERE INDUSTRY IS NULL OR INDUSTRY ='';
SELECT * FROM WORKING_LAYOFFS_2 WHERE COMPANY='AIRBNB';

UPDATE WORKING_LAYOFFS_2
SET INDUSTRY= NULL WHERE INDUSTRY='';

SELECT * FROM 
WORKING_LAYOFFS_2 T1
JOIN WORKING_LAYOFFS_2 T2
	ON T1.COMPANY=T2.COMPANY
WHERE T1.INDUSTRY IS NULL
AND T2.INDUSTRY IS NOT NULL;

UPDATE WORKING_LAYOFFS_2 T1
JOIN WORKING_LAYOFFS_2 T2
	ON T1.COMPANY=T2.COMPANY
SET T1.INDUSTRY=T2.INDUSTRY 
WHERE T1.INDUSTRY IS NULL 
AND T2.INDUSTRY IS NOT NULL;

SELECT * FROM WORKING_LAYOFFS_2 WHERE COMPANY='AIRBNB';


SELECT * FROM WORKING_LAYOFFS_2 WHERE TOTAL_LAID_OFF IS NULL AND PERCENTAGE_LAID_OFF IS NULL;
DELETE FROM WORKING_LAYOFFS_2 WHERE TOTAL_LAID_OFF IS NULL AND PERCENTAGE_LAID_OFF IS NULL;


ALTER TABLE WORKING_LAYOFFS_2
DROP COLUMN ROW_NUM;

SELECT * FROM WORKING_LAYOFFS_2;